# Setup

Install dependencies:

```
poetry install
```

Start Jupyter server:

```
poetry run jupyter notebook --notebook-dir $(pwd)
```

Start presentation:

```
poetry run jupyter nbconvert --to slides vector-intro.ipynb --post serve
```

In [24]:
# %load_ext autoreload
# %autoreload 2

In [25]:
from typing import List
from IPython.core.display import HTML
import helpers
import os
import warnings
import pandas as pd
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

warnings.filterwarnings("ignore")
os.environ[
    "TOKENIZERS_PARALLELISM"
] = "true"  # display warnings for tokenizer

# Vector Embedding Introduction


* [Thomas Fuchs](thomas.fuchs@nosto.com), Data Scientist
* [Georg M. Sorst](georg.sorst@nosto.com), Head of Search Engineering

<p style="text-align: center;"><img src="Nosto_hr_magenta.svg" style="height: 50%; width: 50%; margin-left: auto; margin-right: auto;"/></p>

<p style="text-align: center;">Formerly known as:</p>

<p style="text-align: center;"><img src="Findologic_Logo_Dark.svg" style="height: 15%; width: 15%; margin-left: auto; margin-right: auto;"/></p>

# Keyword Search

Keyword search compares query words with document words.

🔎 _**notebook**_ 

📄 _This **notebook** is perfect for your business needs_ ✅

But it has no concept of similarity.

🔎 _**notebook**_ 

📄 _Enjoy the latest games with this high-performance **laptop**_ ❌

Keyword search uses an _Inverted Index_ that maps document terms to documents.

Documents:
1. This notebook is perfect for your business needs with a battery to last a work day.
2. Enjoy the latest games with this high-performance laptop on the go with a high-performance battery.

| Term     | Document |
|----------|----------|
| notebook | #1       |
| laptop   | #2       |
| business | #1       |
| gaming   | #2       |
| battery  | #1, #2   |
| ….       | …        |

By default, keyword search will lookup _exact_ terms in the index.

1. This notebook is perfect for your business needs with a battery to last a work day.
2. Enjoy the latest games with this high-performance laptop on the go with a high-performance battery.

| Query             | Result   | Reason          |
|-------------------|----------|-----------------|
| battery           | [#1, #2] |                 |
| notebook          | [#1]     |                 |
| Notebook          | []       | Wrong case      |
| notebooks         | []       | Plural          |
| notbok            | []       | Typo            |
| business notebook | [#1]     |                 |
| business laptop   | []       | Missing synonym |

Text analysis can make this more user-friendly.

|                                                                | Query                                      | Document                                                |
|----------------------------------------------------------------|--------------------------------------------|---------------------------------------------------------|
|                                                                | office laptops                             | This notebook is perfect for your business needs        |
| **Tokenization**<br />Break text into tokens                   | office, laptops                            | This, notebook, is, perfect, for, your, business, needs |
| **Lowercasing**                                                | office, laptops                            | this, notebook, is, perfect, for, your, business, needs |
| **Stopwords**<br />a, the, this, for                           | office, laptops                            | notebook, perfect, business, needs                      |
| **Stemming**<br />singular, plurar                             | office, laptop                             | notebook, perfect, business, need                       |
| **Synonyms**<br />office <-> business<br />laptop <-> notebook | office, business, laptop, notebook         | notebook, perfect, business, need                       |
| **Result**                                                     | office, **business**, laptop, **notebook** | **notebook**, perfect, **business**, need               |

🔎 _**office laptops**_ 

📄 _This **notebook** is perfect for your **business** needs_ ✅

Text analysis is not trivial to setup.

Text analysis is different per language e.g. tokenization, stemming.

Synonyms require constant maintenance.

# Vector Search

Vector search looks for _similar_ words.

🔎 _**notebook**_

📄 _This **notebook** is perfect for your business needs_ ✅

📄 _Enjoy the latest games with this high-performance **laptop**_ ✅

Vector search can handle tokenization, stemming, typos, synonyms out of the box.

# Vector Embeddings

Special Neural Nets can transform text into vectors.

These vectors can be _embedded_ into a common vector space.

This makes it possible to discover semantic relationships between texts.

Let's define some words.

In [26]:
words = [
    "queen",
    "king",
    "prince",
    "princes",
    "man",
    "woman",
    "boy",
    "girl",
    "red",
    "green",
    "blue",
    "palace",
]

Transforming words into vectors is easy with Python.

Many free models exist to perform vector embedding.

In [27]:
def embed(texts):
    model_name = "all-MiniLM-L6-v2"
    model = SentenceTransformer(
        model_name,
        device=helpers.get_torch_device_name(),  # Optional: if you want to run this on GPU
    )
    return model.encode(texts)

The resulting vector is represented as a multidimensional array in Python.

All vectors share the same dimensionality, for this model it's 384 dimensions.

In [28]:
pd.DataFrame(embed(words[0])) #words[0] == Quen

            0
0    0.035487
1   -0.065605
2   -0.009935
3    0.031590
4   -0.013387
..        ...
379  0.026038
380  0.091385
381 -0.053889
382 -0.031242
383 -0.086961

[384 rows x 1 columns]

Each word is transformed into a vector so that we can discover semantic relationships.

In [29]:
pd.DataFrame(
    {"Sentence": words, "Encoding": list(embed(words))}
).head(3)

  Sentence                                           Encoding
0    queen  [0.03548696, -0.06560465, -0.009934981, 0.0315...
1     king  [-0.059599336, 0.050512414, -0.06951014, 0.079...
2   prince  [-0.036828797, 0.041281953, 0.041856598, 0.041...

Let's visualize the vectors to show their relationships.

But 384-dimensional vectors cannot be plotted on a 2-dimensional screen.

Principal Component Analysis (PCA) can reduce the number of dimensions from 384 to 2.

In [30]:
word_samples = words[0:3]
embeddings = embed(word_samples)
reduced_embeddings = PCA(n_components=2).fit_transform(embeddings)
pd.DataFrame(
    {"Words": word_samples, "Encoding": list(reduced_embeddings)}
)

    Words                    Encoding
0   queen   [-0.2934045, -0.38926488]
1    king    [-0.25320098, 0.4088318]
2  prince  [0.54660565, -0.019567026]

In [31]:
import plotly.graph_objects as go
from sklearn.decomposition import PCA


def plot(sentences, embeddings, color="blue", existing_figure=None):
    # Perform PCA
    pca = PCA(n_components=2)
    reduced_embeddings = pca.fit_transform(embeddings)

    # Create annotations for each sentence
    annotations = []
    for i, sentence in enumerate(sentences):
        words = sentence.split()
        annotation = " ".join(words[:3]) + ("..." if len(words) > 3 else "")
        annotations.append(annotation)

    my_figure = existing_figure or go.Figure()

    # Add the reduced embeddings as a scatter plot
    my_figure.add_trace(go.Scatter(
        x=reduced_embeddings[:, 0],
        y=reduced_embeddings[:, 1],
        mode="markers+text",
        text=annotations,  # Add the annotations
        textposition="top center",
        marker=dict(color=color, size=10)
    ))

    # Update axes and title
    my_figure.update_layout(
        title="2D PCA of Sentence Embeddings",
        xaxis_title="Principal Component 1",
        yaxis_title="Principal Component 2",
        showlegend=False,
        height=600,
        width=800
    )

    # Only show the figure if none was provided
    if existing_figure is None:
        my_figure.show()

When visualizing the reduced vectors, clear semantic clusters appear.

In [33]:
plot(words, embed(words))

# Sentence Embeddings

We can not only embed words but entire sentences and documents.

Let's define some documents and embed them.

In [34]:
import pandas as pd

documents = [
    "Vector embeddings are mathematical representations of objects, often words or phrases, in a high-dimensional space. By mapping similar objects to proximate points, embeddings capture relationships and semantic meaning. Commonly used in machine learning and natural language processing tasks, methods like Word2Vec, GloVe, and FastText have popularized their application, enabling advancements in text analysis, recommendation systems, and more.",
    "Keyword search refers to the process of locating information in a database, search engine, or other data repository by specifying particular words, phrases, or symbols. In the digital realm, it's foundational to search engines like Google and Bing. The search results are typically ranked based on relevance, which is determined using various algorithms that consider factors like frequency, location, and link structures. Keyword search is integral for navigating the vast expanse of online information, aiding users in retrieving relevant data efficiently.",
    "Sandwiches are a popular type of food consisting of one or more types of food, such as vegetables, sliced meat, or cheese, placed between slices of bread. They can range from simple combinations like peanut butter and jelly to more complex gourmet creations. Originating from England in the 18th century, sandwiches have become a staple in many cultures worldwide, prized for their convenience and versatility. Variations exist based on regional preferences, ingredients, and preparation methods.",
    "Data science is an interdisciplinary field that leverages statistical, computational, and domain-specific expertise to extract insights and knowledge from structured and unstructured data. It encompasses various techniques from statistics, machine learning, data mining, and big data technologies to analyze and interpret complex data. Data science has applications across numerous sectors, including healthcare, finance, marketing, and social sciences, driving decision-making, predictive analytics, and artificial intelligence advancements. Its growing significance in today's data-driven world has led to the rise of specialized tools, methodologies, and educational programs.",
    "Neural networks are a class of machine learning models inspired by the biological neural networks of animal brains. They consist of interconnected layers of nodes, or neurons, which process input data through a series of transformations and connections to produce output. Neural networks are particularly adept at recognizing patterns, making them useful for a wide range of applications such as image and speech recognition, natural language processing, and predictive analytics. The development of deep neural networks, which contain multiple hidden layers, has been central to the field of deep learning and has significantly advanced the capabilities of artificial intelligence systems.",
    "Pasta is a staple food of traditional Italian cuisine, with the first reference dating to 1154 in Sicily. It is typically made from an unleavened dough of durum wheat flour mixed with water or eggs and formed into sheets or various shapes, then cooked by boiling or baking. Pasta is versatile and can be served with a variety of sauces, meats, and vegetables. It is categorized in two basic styles: dried and fresh. Popular around the world, pasta dishes are central to many diets and come in numerous shapes like spaghetti, penne, and ravioli.",
    "Soup is a liquid food, generally served warm or hot (but also cold), that is made by combining ingredients such as meat and vegetables with stock, juice, water, or another liquid. Soups are inherently diverse, ranging from rich, cream-based varieties to brothy and vegetable-laden concoctions. They are often regarded as comfort food and can be served as a main dish or as an appetizer, with regional and cultural variations like the Spanish gazpacho, Japanese miso soup, and Russian borscht.",
    "A casserole is a comprehensive one-dish meal baked in a deep, ovenproof dish with a glass or ceramic base. It typically includes a combination of meats, vegetables, starches like rice or potatoes, and a binding agent like a soup or sauce. Topped with cheese or breadcrumbs for a crispy crust, casseroles are appreciated for their convenience and the ability to meld flavors during the baking process. They are a fixture in many cultures and are particularly beloved as home-cooked comfort foods, often featuring in communal gatherings and family dinners.",
]

pd.DataFrame(
    {"Sentence": documents, "Encoding": list(embed(documents))}
).head(3)

,Sentence,Encoding
0,Vector embeddings are mathematical representat...,"[-0.0016682168, -0.06941, -0.026505126, 0.0056..."
1,Keyword search refers to the process of locati...,"[0.019650575, -0.062715, -0.045780774, -0.0006..."
2,Sandwiches are a popular type of food consisti...,"[-0.04432277, -0.0237825, 0.03651129, -0.01122..."

Again, semantic clusters appear when visualizing the vectors in a 2D-space.

In [35]:
import plotly.graph_objects as go


def plots(sentences_embeddings_color):
    figure = go.Figure()
    for sentences, embeddings, color in sentences_embeddings_color:
        plot(sentences, embeddings, color, figure)
    figure.show()

In [36]:
plots([(documents, embed(documents), "green")])

# Information Retrieval

Similar documents have similar vectors.

This characteristic can be used to retrieve related documents for an input text.

Let's start by defining some search queries.

In [41]:
queries = [
    "information retrieval",
    "machine learning",
    "cooking",
]
plots([(queries, embed(queries), "red")])

In [38]:
# TODO: Fix graph above

Visualizing documents and queries in one space uncovers semantic relations.

Each query is closests to its most relevant documents.

In [39]:
plots(
    [
        (documents, embed(documents), "green"),
        (queries, embed(queries), "red"),
    ]
)

# HuggingFace 🤗

HuggingFace is the GitHub of AI models.

Thousands freely available models for many purposes.

![HuggingFace](data/HuggingFace.png)

# Simply Search

## Load Data
Firstly, we need to load data. To do this, we use the product data from a [customer](https://pinklily.com/).

In [15]:
merchant_id = "shopify-26890272823"
path_name = f"data/{merchant_id}_products.pkl"
df_products = pd.read_pickle(path_name).loc[:,["productId",	"name"	,"description"]]

In [16]:
df_products.head(3)

,productId,name,description
0,4544264339511,Chelsie Medium Wash Jeans FINAL SALE,Details\nMedium wash denim jeans\nFabric has s...
1,4544264732727,Nothing But The Best White Bodysuit,Details White long sleeve bodysuit Fabric has ...
2,4544267976759,Chelsie Dark Wash Jeans FINAL SALE,Details\nDark wash denim skinny jeans\nFabric ...

## Embed Data
The next step is to embed the data.  
In a real-world scenario, we use specialised programs such as ElasticSearch to apply embeddings and assign weights to different fields.  
The advantage of using embeddings is that different fields can be combined in advance to achieve a favourable result.

In [17]:
combine_fields = (
    lambda x: f"Product name = {x['name']}\n"
    f"Description = {x['description']}\n"
)

In [18]:
model = SentenceTransformer(
    "thenlper/gte-large",
    device=helpers.get_torch_device_name(),  # Optional: if you want to run this on GPU
)
df_for_search = pd.DataFrame()
df_for_search["base_string"] = df_products.apply(
    combine_fields, axis=1
).values
df_for_search["embeddings"] = list(
    model.encode(df_for_search["base_string"].values)
)

In [19]:
df_for_search.head(5).style

In [20]:
df_for_search = pd.concat(
    [df_for_search, df_products.loc[:, ["name", "productId"]]],
    axis=1,
)

## Calculate Similarity
The most frequently employed method for assessing similarity is through [cosine_similarity](https://en.wikipedia.org/wiki/Cosine_similarity) or cosine distance.  
$ \text{cosinus-similarity}=S_{C}(A,B):=\cos(\theta)={\mathbf {A} \cdot \mathbf {B} \over \|\mathbf { A} \|\|\mathbf{B}\|}= \frac{\sum \limits_{i=1}^{n}{A_{i}B_{i}}}{{\sqrt {\sum \limits_{i=1}^{n}{A_{i}^{2}}}}{\sqrt {\sum \limits_{i=1}^{n}{B_{i}^{ 2}}}}}\in [-1,1]$  
$\text{cosinus-distance}=D_{C}(A,B):=1-S_{C}(A,B)$  
**ATTENTION: not really a distance-metric**  
We can leverage the pre-existing functionality provided by sklearn for this purpose.

In [21]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

np.random.seed(1)
dimension = 2
num_vectors = 4
df_show_cos = pd.DataFrame(
    {
        "embeddings": np.random.uniform(
            0, 1, size=(num_vectors, dimension)
        ).tolist(),
        "color_col": ["products"] * (num_vectors - 1) + ["query"],
    }
)
df_show_cos["similarity"] = cosine_similarity(
    [df_show_cos["embeddings"].iloc[-1]],
    df_show_cos["embeddings"].tolist(),
)[0]
fig = helpers.color_embedings_df(
    df_show_cos,
    color_col="color_col",
    dimensions=dimension,
    add_vectors=True,
    hover_data=["similarity"],
)

In [22]:
fig.show()

## Approximate calculation of similarity
With [ANNOY](https://github.com/spotify/annoy) (Approximate Nearest Neighbors Oh Yeah) we can significantly increase the efficiency of our search processes.  
To achieve this, we create an index that is not only very powerful, but also compact.

In [23]:
from annoy import AnnoyIndex


def get_annoy_index(
    df: pd.DataFrame, n_trees: int = 20
) -> AnnoyIndex:
    embeddings = df["embeddings"]
    index_ann = AnnoyIndex(
        len(embeddings[0]), "angular"
    )  # Length of item vector that will be indexed
    for i, v in embeddings.items():  # ATTENTION index must be int
        index_ann.add_item(i, v)
    index_ann.build(
        n_trees=n_trees
    )  # More trees gives higher precision when querying
    return index_ann

In [24]:
ann_index: AnnoyIndex = get_annoy_index(df_for_search, n_trees=20)

#### Show entries of annoy index

In [25]:
n_items = ann_index.get_n_items()
pd.DataFrame(
    [ann_index.get_item_vector(x) for x in range(n_items)],
)

,0,1,2,3,4,5,6,7,8,9,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
0,-0.000964,-0.002004,-0.011685,-0.004452,-0.023053,0.007588,-0.001544,0.042610,0.029276,0.036479,...,0.035979,-0.075278,-0.044081,-0.024372,0.041246,0.047685,0.045876,-0.020487,0.005929,-0.026166
1,-0.002225,-0.007242,-0.010705,-0.009306,-0.020888,0.007443,-0.001728,0.033834,0.009070,0.013562,...,0.030267,-0.071721,-0.028778,-0.026805,0.034955,0.054812,0.042883,-0.026238,0.024674,-0.038617
2,-0.006444,-0.005713,0.005327,-0.003019,-0.024472,-0.000091,-0.001735,0.035456,0.020791,0.044488,...,0.036069,-0.065567,-0.050655,-0.019731,0.038968,0.050774,0.055868,-0.017511,0.002768,-0.020069
3,-0.011602,-0.020093,-0.022610,-0.007701,-0.019643,-0.000858,0.001654,0.032952,0.019622,0.039792,...,0.038744,-0.061465,-0.038190,-0.016164,0.057104,0.054939,0.053581,-0.019757,-0.000992,-0.005976
4,-0.003198,0.007124,0.001214,-0.019860,-0.022174,-0.006938,-0.008835,0.046789,0.012924,0.034184,...,0.042008,-0.061549,-0.035749,-0.018659,0.040147,0.045198,0.045986,-0.008769,0.006613,-0.024698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4444,-0.018165,-0.007819,-0.015711,-0.000615,-0.016588,-0.011449,-0.004705,0.038970,0.028605,0.038145,...,0.022073,-0.072572,-0.032724,-0.009049,0.059284,0.041910,0.024572,-0.008374,0.010207,-0.043363
4445,-0.010462,0.000417,-0.001110,0.014649,-0.004167,-0.011309,0.013109,0.047703,0.033681,0.028913,...,0.029207,-0.061211,-0.051184,-0.015537,0.059562,0.038147,0.029435,-0.012207,0.001015,-0.030669
4446,0.013239,-0.020012,-0.013385,-0.002551,-0.001049,-0.007911,0.009968,0.019417,0.025630,0.028909,...,0.045338,-0.050530,-0.028419,-0.011816,0.054819,0.059834,0.025967,-0.009309,-0.019529,-0.035229
4447,0.008345,-0.031816,-0.029309,0.002701,0.000503,-0.013075,0.013326,0.019450,0.022728,0.043193,...,0.045941,-0.071635,-0.034241,0.000599,0.066021,0.051151,0.027290,-0.023803,-0.017934,-0.032528
4448,-0.004657,-0.002069,0.006446,0.010509,-0.001880,-0.020791,0.010497,0.036576,0.020018,0.040203,...,0.042946,-0.063213,-0.033221,-0.012975,0.061823,0.052368,0.018940,-0.014928,0.006128,-0.024946

In [26]:
df_for_search["annoy_cluster"] = helpers.calc_cluster(ann_index)
fig_annoy = helpers.color_embedings_df(
    df_for_search, "annoy_cluster", hover_data=["name"], dimensions=3
)

In [27]:
fig_annoy.show()

In [5]:
#TODO: Explain why Annoy clusters the vectors: To turn 400 cosine similarities for 400 products into 21 comparisons (when building 20 clusters)

### time comparison
![](data/time_to_calculate_similarity_100_queries_all-MiniLM-L6-v2.png)

### Query with Annoy

In [28]:
def get_similar_products_annoy(
    ann_index: AnnoyIndex, query: str, top_n: int = 5
) -> List[int]:
    query_embedding = model.encode(query)
    nns = ann_index.get_nns_by_vector(query_embedding, top_n)
    return nns

In [29]:
query_easy = "hoodie"
model.encode(query_easy)

array([-0.01272601, -0.00032983, -0.01062606, ..., -0.01671979,
       -0.01496496, -0.01919532], dtype=float32)

In [30]:
sim_prod = df_products.loc[
    get_similar_products_annoy(ann_index, query_easy, 5), :
]
html_easy = helpers.display_images_and_names(
    sim_prod,
    merchant_id,
    f"ANNOY VectorSearch for:<br>'{query_easy}'",
)

In [31]:
display(HTML(html_easy))

### Complex Query with Annoy

In [32]:
query_complex = "For my Frau, I need a schwarze Jumpsuit"

In [33]:
sim_prod = df_products.loc[
    get_similar_products_annoy(ann_index, query_complex, 5)[0:5]
]
html_complex = helpers.display_images_and_names(
    sim_prod,
    merchant_id,
    f"ANNOY VectorSearch for:<br>'{query_complex}'",
)

In [34]:
display(HTML(html_complex))

### Same query - same index --- more results

In [35]:
sim_prod = df_products.loc[
    get_similar_products_annoy(ann_index, query_complex, 500)[0:5]
]
html_complex_more_result = helpers.display_images_and_names(
    sim_prod,
    merchant_id,
    f"ANNOY VectorSearch for:<br>'{query_complex}'",
)

In [36]:
display(HTML(html_complex_more_result))

### Same query - index with more tree --- few results

In [37]:
ann_index_more_tree: AnnoyIndex = get_annoy_index(
    df_for_search, n_trees=200
)
sim_prod = df_products.loc[
    get_similar_products_annoy(ann_index_more_tree, query_complex, 5)[
        0:5
    ]
]
html_complex_more_tree = helpers.display_images_and_names(
    sim_prod,
    merchant_id,
    f"ANNOY VectorSearch for:<br>'{query_complex}'",
)

In [38]:
display(HTML(html_complex_more_tree))

In [6]:
#TODO: Explain how to build strings for vectorization e.g. concatenate all product texts

## Vector Search: Advantages and Disadvantages

### Disadvantages
1. **Complexity:**
    * Implementation and optimization of vector search algorithms can be complex, requiring specialized knowledge.  
3. **Resource Intensive:**
    * Computationally intensive, demanding significant computing resources for large-scale applications.  
5. **Quality of Embeddings:**
    * The effectiveness of vector search heavily depends on the quality of the embeddings, which may require fine-tuning.  
7. **Interpretability:**
    * Results may lack interpretability, making it challenging to understand the reasoning behind specific search outcomes.

### Advantages
1. **Efficiency:**
    * Vector search allows for fast and efficient similarity searches in high-dimensional spaces.  
3. **Scalability:**
    * Well-suited for large datasets and can scale effectively with the growing volume of data.  
5. **Flexibility:**
    * Adaptable to various data types, making it versatile for different domains such as **image, text, and audio**.  
7. **Semantic Understanding:**
    * Captures semantic relationships, enabling more meaningful and context-aware search results.